export const horario = [
    {
        id: 1,
        hora: '00:00',
        tarefa: '',
        categoria: 'Estudos',
    },
    {
        id: 2,
        hora: '01:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 3,
        hora: '02:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 4,
        hora: '03:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 5,
        hora: '04:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 6,
        hora: '05:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 7,
        hora: '06:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 8,
        hora: '07:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 9,
        hora: '08:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 10,
        hora: '09:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 11,
        hora: '10:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 12,
        hora: '11:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 13,
        hora: '12:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 14,
        hora: '13:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 15,
        hora: '14:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 16,
        hora: '15:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 17,
        hora: '16:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 18,
        hora: '17:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 19,
        hora: '18:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 20,
        hora: '19:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 21,
        hora: '20:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 22,
        hora: '21:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 23,
        hora: '22:00',
        tarefa: '',
        categoria: '',
    },
    {
        id: 24,
        hora: '23:00',
        tarefa: '',
        categoria: '',
    },
]